Print a warning if ChangeLog isn't found on make dist
Tweak HOWTO_RELEASE file to make sure a ChangeLog is included

git-svn-id: http://svn.osgeo.org/geos/branches/3.6@4322 5242fede-7e19-0410-aef8-94bd7d2200fb

diff --git a/Makefile.am b/Makefile.am
--- a/Makefile.am
+++ b/Makefile.am
@@ -41,7 +41,10 @@ gen-ChangeLog:
 	elif test -d .svn; then \
 		svn2cl --authors=authors.svn -i -o $${owd}/ChangeLog; \
 	elif test -f ChangeLog; then \
+		echo "NOTE: distributing ChangeLog found in source dir"; \
 		cp ChangeLog  $${owd}/ChangeLog; \
+	else \
+		echo "WARNING: could not find a ChangeLog" >&2; \
 	fi
 
 apidoc doxygen:
